export const CHANGE_SELECTED_STOCK = 'CHANGE_SELECTED_STOCK';
export const GET_USER_STOCKLIST = 'GET_USER_STOCKLIST';
export const GET_SEARCH_STOCKLIST = 'GET_SEARCH_STOCKLIST';
export const ADD_STOCK_TO_LIST = 'ADD_STOCK_TO_LIST';
export const SET_USER = 'SET_USER';